### ISSUE TITLE
Unable to run git clone

### ISSUE THREAD

**Issue by tyli1** [AnanthVivekanand/spotify-adblock-macos#1]
When I try to run git clone https://AnanthVivekanand/spotify-adblock-macos.git && cd spotify-adblock-macos, terminal spits out 
Cloning into 'spotify-adblock-macos'...
fatal: unable to access 'https://AnanthVivekanand/spotify-adblock-macos.git/': Could not resolve host: AnanthVivekanand

Unsure of how to proceed.

**Comment by P0SlX** [comment]
If you want, you can just download the zip file if you just want to use it, make sure tu have node installed 
```$ brew install node```

**Comment by tyli1** [comment]
Thanks for the quick reply! I have installed node and downloaded the zip file. Now what? What do I open in the zip file? Do I need to change the proxy and still run the commands? Sorry for the questions. Would love to try your program but not sure how to start it.

Thanks again!

**Comment by AnanthVivekanand** [comment]
Ah I see, the git clone command had a typo. I’ll fix that in a commit to the README soon. 

Extract the zip and cd into the folder. Then run `node index.js` to start the proxy. Then update the proxy settings on Spotify. 

I’ll fix the git clone command and add more detailed instructions in a commit later.

**Comment by tyli1** [comment]
Great! I got the proxy running but now songs are not playing in spotify. I believe I have followed all your instructions. Is there anything I can be doing wrong?

**Comment by AnanthVivekanand** [comment]
Hmm, you might need to install the npm dependencies: run `npm i http-proxy micromatch` and then try running the `node index.js` again.

**Comment by tyli1** [comment]
Still not working. But thanks for trying!
