### ISSUE TITLE
Uninstall instructions requested

### ISSUE THREAD

**Issue by philemonlives** [AnanthVivekanand/spotify-adblock-macos#13]
Hi Ananth,

Appreciate your effort in developing this solution.

I am running the latest Mac OS (Catalina) and the latest Spotify. Executed your code as instructed, but Spotify doesn't play anything after I did this. Tried installing an older version of Spotify (close to the one you have) but still facing the same issue.

I would like to undo the changes made as per your instructions. Could you please include instructions for uninstalling or undoing the changes, in the readme?

Thank you!

**Comment by philemonlives** [comment]
never mind, I figured it out :) thanks

**Comment by AnanthVivekanand** [comment]
For future reference, all the code is contained within the git clone, and nothing is "installed" on the system outside of it.

So reverting the instructions is as simple as deleted the cloned repo and then changing the Spotify proxy settings back to "No proxy"

I'm open to a PR to add this to the readme or I'll get around to it eventually.
