### ISSUE TITLE
can't play music

### ISSUE THREAD

**Issue by octieuway** [AnanthVivekanand/spotify-adblock-macos#3]
app can't load music. thanks.

**Comment by AnanthVivekanand** [comment]
Hi there! 

Can you give me a little more information about what the console says? A screenshot of the blocked domains would help.

**Comment by octieuway** [comment]
![Screen Shot 2020-03-31 at 16 38 15](https://user-images.githubusercontent.com/60751805/78011741-2efab300-736e-11ea-8d47-30f8a9b83682.png)
![Screen Shot 2020-03-31 at 16 38 15](https://user-images.githubusercontent.com/60751805/78011886-65383280-736e-11ea-89c5-b3b46ac0bec9.png)
![Screen Shot 2020-03-31 at 16 38 15](https://user-images.githubusercontent.com/60751805/78012268-eabbe280-736e-11ea-97b3-4ee8a154c4a1.png)


Is this a sceenshot you want?
I just try a new instruction in readme. But Spotify can't not playing a song.

Thanks for your reply.

**Comment by AnanthVivekanand** [comment]
Do other things in spotify load like playlists or your home view? Do any songs play? Or do none of them play?

**Comment by vladdenisov** [comment]
Faced the same issue.
@octieuway Could you test workability by adding `login5.spotify.com` to `whitelist.js`?

**Comment by Defirence** [comment]
@vladdenisov I tried this but it looks like npm start fails to load, highlighting the line in whitelist.js that I added to test with. Please see attached. NPM logs were sanitized to remove my real name, but the full log is included as well.
<img width="714" alt="Screenshot 2020-04-29 at 10 57 34" src="https://user-images.githubusercontent.com/33593621/80579214-efc18f80-8a09-11ea-9092-7753bd731850.png">
<img width="1004" alt="Screenshot 2020-04-29 at 10 57 42" src="https://user-images.githubusercontent.com/33593621/80579219-f2bc8000-8a09-11ea-80e4-e17e3f3722ff.png">
[2020-04-29T08_56_25_366Z-debug.log](https://github.com/AnanthVivekanand/spotify-adblock-macos/files/4550702/2020-04-29T08_56_25_366Z-debug.log)

**Comment by vladdenisov** [comment]
@Defirence you need to put comma after previous string. Like this:
```
"video-fa.scdn.co",
"login5.spotify.com
```

**Comment by Defirence** [comment]
@vladdenisov Ah my bad, I added the comma where it was missing along with login5 and Spotify works again. Music that is locally cached and also new non-cached songs are playing. Thanks! Now just crossing my fingers that it'll stay this way and not break again. 
<img width="960" alt="Screenshot 2020-04-29 at 11 23 13" src="https://user-images.githubusercontent.com/33593621/80580584-108ae480-8a0c-11ea-93bc-ae73fd8511d2.png">

**Comment by vladdenisov** [comment]
Some reported ads coming up with this address whitelisted. So, please, report if anything goes wrong.

**Comment by Defirence** [comment]
Will do so, I have the Issue link bookmarked so if anything does come up I'll drop another comment on here.

**Comment by AnanthVivekanand** [comment]
I'm going to close this issue since it seems like that adding `login5.spotify.com` fixes this issue. However, I'm not going to add it onto the code in this repo since it allows some ads through as discovered on #7.

I think the `mitm-proxy` branch has a fix for this, @vladdenisov can you take a look at it? I've been using it for a day, with all spotify functionality working and no ads.

**Comment by Defirence** [comment]
Just dropping a comment for record-keeping and future releases.

Whitelisting `login5.spotify.com` allows ads to pass through here and there but I've noticed a drastic decrease when using this compared to standard HOSTS file blocking. But as per the last comment and #7 it does allow ads through unfortunately.
