### ISSUE TITLE
Trouble starting npm start on macos

### ISSUE THREAD

**Issue by swan11jf** [AnanthVivekanand/spotify-adblock-macos#8]
Here's the following error message I get:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/screelt/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/screelt/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/screelt/.npm/_logs/2020-05-14T22_09_45_398Z-debug.log

Can include log if requested

**Comment by AnanthVivekanand** [comment]
You have to cd inside the cloned project. Run the command "ls" and you should see spotify-adblock-macos. Then run "cd spotify-adblock-macos" 

After cd-ing inside the directory then run npm i and proceed from there.

**Comment by swan11jf** [comment]
Thanks for your reply - I must have done something stupid...
